# Generated by Django 4.1.1 on 2022-11-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='message',
            field=models.TextField(default='', max_length=200),
        ),
    ]
