# Generated by Django 4.1.1 on 2022-11-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_shoppingcart_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_time_int',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='start_time_int',
            field=models.IntegerField(default=0),
        ),
    ]
