# Generated by Django 4.1.1 on 2022-11-19 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_course_end_time_int_course_start_time_int'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date_published',
        ),
        migrations.AddField(
            model_name='comment',
            name='toUser',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='toUser', to='main.myuser'),
        ),
    ]
