# Generated by Django 4.1.1 on 2022-11-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_comment_date_published_comment_touser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentBody',
            field=models.TextField(max_length=200),
        ),
    ]
