# Generated by Django 4.1.1 on 2022-11-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_comment_commentbody'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='schedule',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
