# Generated by Django 4.1.1 on 2022-11-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_myuser_numfriends'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='numFriends',
            field=models.SmallIntegerField(default=0),
        ),
    ]
